<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\..\assets\AMacQ.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup Condition="'$(AuthorEdition)' == 'true'">
    <DefineConstants>$(DefineConstants);AUTHOR_EDITION</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <EmbeddedResource Include="..\..\assets\AMacQ.ico" LogicalName="AMacQConfigEditor.Resources.AMacQ.ico" />
    <EmbeddedResource Include="Resources\Sorin 24.1 S10.zip" LogicalName="AMacQConfigEditor.Resources.SorinPackage.zip" />
  </ItemGroup>
</Project>
